import pygame
pygame.mixer.init()

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
#asteroid variables
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2.0  # seconds
ASTEROID_STARTING_VELOCITY = 0
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
#player variables
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 200
PLAYER_MAX_SPEED = 200
PLAYER_SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_TIMER = 0.3
PLAYER_DEATH_TIMER = 1.0
#sounds
BANG = pygame.mixer.Sound("./sounds/bang.wav")
FIRE = pygame.mixer.Sound("./sounds/fire.wav")
